In [1]:
#pip install pandas

In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35, 28, 31, 36],
    "City": ["New York", "Los Angeles", "Chicago", "New York", "Los Angeles", "Chicago"],
    "Sales": [200, 150, 100, 300, 250, 200]
}
df = pd.DataFrame(data)

In [3]:
print(df.head())

      Name  Age         City  Sales
0    Alice   25     New York    200
1      Bob   30  Los Angeles    150
2  Charlie   35      Chicago    100
3    Alice   28     New York    300
4      Bob   31  Los Angeles    250

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   City    6 non-null      object
 3   Sales   6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes
None

In [5]:
pd.pivot_table(df, values="Sales", index="City", columns="Name",
               aggfunc="mean",
               fill_value=0, margins=True, dropna=True,
               margins_name="Total", observed=False)

Name         Alice    Bob  Charlie  Total
City
Chicago        0.0    0.0    150.0  150.0
Los Angeles    0.0  200.0      0.0  200.0
New York     250.0    0.0      0.0  250.0
Total        250.0  200.0    150.0  200.0

In [6]:
import pandas as pd

# Sample data
data = {
    "Date": ["2023-01-01", "2023-01-01", "2023-01-01", "2023-01-01", "2023-01-02", "2023-01-02"],
    "City": ["New York", "New York", "New York", "Los Angeles", "New York", "Los Angeles"],
    "Sales": [200, 100, 300, 150, 300, 250]
}

df = pd.DataFrame(data)

# Creating a pivot table
pivot = pd.pivot_table(df, values="Sales", index="Date", columns="City",
                       aggfunc="sum")
print(pivot)

City        Los Angeles  New York
Date
2023-01-01          150       600
2023-01-02          250       300

In [7]:
data = {
    "Date": ["2023-01-01", "2023-01-01", "2023-01-01", "2023-01-01", "2023-01-02", "2023-01-02"],
    "City": ["New York", "New York", "New York", "Los Angeles", "New York", "Los Angeles"],
    "Product": ["A", "A", "B", "B", "A", "B"],
    "Sales": [200, 100, 300, 150, 300, 250]
}

df = pd.DataFrame(data)

# Multi-index pivot table
pivot = pd.pivot_table(df, values="Sales", index=["Date", "City"], columns="Product",
                       aggfunc="sum")
print(pivot)

Product                     A      B
Date       City
2023-01-01 Los Angeles    NaN  150.0
           New York     300.0  300.0
2023-01-02 Los Angeles    NaN  250.0
           New York     300.0    NaN

In [8]:
# Using multiple aggregation functions
pivot = pd.pivot_table(df, values="Sales", index="Date", columns="City",
                       aggfunc=["sum", len])
print(pivot)

                   sum                  len
City       Los Angeles New York Los Angeles New York
Date
2023-01-01         150      600           1        3
2023-01-02         250      300           1        1

In [9]:
# Filling missing values with 0
pivot = pd.pivot_table(df, values="Sales", index="Date", columns="City",
                       aggfunc="sum", fill_value=0)
print(pivot)

City        Los Angeles  New York
Date
2023-01-01          150       600
2023-01-02          250       300

In [10]:
# Styling the pivot table
pivot.style.format("${:.2f}").background_gradient(cmap="viridis")

In [11]:
# Renaming index and columns
pivot.rename(columns={"New York": "NY", "Los Angeles": "LA"}, inplace=True)
pivot.rename_axis("City", axis="columns", inplace=True)
pivot.rename_axis("Sales Date", axis="index", inplace=True)
print(pivot)

City         LA   NY
Sales Date
2023-01-01  150  600
2023-01-02  250  300

In [12]:
# Adding margins
pivot = pd.pivot_table(df, values="Sales", index="Date", columns="City",
                       aggfunc="sum", margins=True)
print(pivot)

City        Los Angeles  New York   All
Date
2023-01-01          150       600   750
2023-01-02          250       300   550
All                 400       900  1300

In [13]:
# Optimizing memory usage
df["Sales"] = df["Sales"].astype("int32")

In [14]:
df["Sales"]

0    200
1    100
2    300
3    150
4    300
5    250
Name: Sales, dtype: int32

In [15]:
df

         Date         City Product  Sales
0  2023-01-01     New York       A    200
1  2023-01-01     New York       A    100
2  2023-01-01     New York       B    300
3  2023-01-01  Los Angeles       B    150
4  2023-01-02     New York       A    300
5  2023-01-02  Los Angeles       B    250

In [30]:
# from google.colab import sheets
# sheet = sheets.InteractiveSheet(df=df)